// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbntkmG8dyOCGVWZfCybGyyqlLr4w7is',
    appId: '1:301334429914:web:4e8454491119860ab125e3',
    messagingSenderId: '301334429914',
    projectId: 'blood-donate-5b844',
    authDomain: 'blood-donate-5b844.firebaseapp.com',
    storageBucket: 'blood-donate-5b844.firebasestorage.app',
    measurementId: 'G-Q1EYR2V4JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Syd1SP3hH8vNqxSjksfQPc5TYsTChcI',
    appId: '1:301334429914:android:1dac091922a31bf8b125e3',
    messagingSenderId: '301334429914',
    projectId: 'blood-donate-5b844',
    storageBucket: 'blood-donate-5b844.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDREiQgFudByO5a98Pj-_yN0nwQlWYmCWc',
    appId: '1:301334429914:ios:279673857048ed03b125e3',
    messagingSenderId: '301334429914',
    projectId: 'blood-donate-5b844',
    storageBucket: 'blood-donate-5b844.firebasestorage.app',
    iosClientId: '301334429914-hqlt77giehlch8v3m2etqf3dk2vvh2q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonate',
  );
}
